### ISSUE TITLE
Define Events for the default Guest User view

### ISSUE THREAD

**Issue by felipdcz** [bernardodiasc/x-world-map#9]
**As a** guest user, 
**I want** to see events when I load the page,
**so that** I start the navigation knowing what's happening,
![001](https://user-images.githubusercontent.com/3913116/181127652-944da1fa-87f0-467b-9290-326cc3e3eb3b.png)

[EDITED]

**Comment by Wtheodoro** [comment]
I can do it.

**Comment by bernardodiasc** [comment]
@felipdcz let's split this issue into 2, alright? It should be fine to deliver them separated given they aren't really related.

@Wtheodoro thanks for jumping on this! Welcome to the contributors team 💪 🚀 

Let me briefly explain a bit of the 2 stories (which should be split /cc @felipdcz):

## Events as default content

> As a guest user,
> I want to see events when I load the page,
> so that I start the navigation knowing what's happening

This one is a quick-win. In the codebase it's just a matter of make the Events as the default content to be on the map. What I noticed more in the screenshot is the label "Events" in the header. Should we included that in the changes @felipdcz?

This story could be added together is thats the case:

> As a guest user,
> I want to see the title "Events" in the header,
> so that I can know what type of content is being displayed in the map

## Create Places content-type

This other tasks is not really a quick-win as it involves changes in the https://github.com/bernardodiasc/x-world-map-api as well. I'd recommend to split this one into another and give us a chance to groom and get some more details of how to proceed. We need to define how this new content type will be in the API and then add the feature to the frontend.

**Comment by felipdcz** [comment]
@bernardodiasc Got it. Please, leave the title 'Events' out for now.

**Comment by Wtheodoro** [comment]
Fixed on this PR https://github.com/bernardodiasc/x-world-map/pull/21

**Comment by bernardodiasc** [comment]
@felipdcz please review updates on https://x-world-map.com/. For a matter of fact, we DO have staging environments, for the fix added that could be had be previewed at https://x-world-9vxuyia77-bernardodiasc.vercel.app/

If there aren't anything else to change for this issue, please close it 💪 

Thanks @Wtheodoro 🚀

**Comment by felipdcz** [comment]
It's great!
Thanks @Wtheodoro , @bernardodiasc
